---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: info
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/fluxcd/flagger
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfofolder
  namespace: info
spec:
  interval: 5m0s
  path: ./kustomize/podinfo
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: info
